# Template formula for a future community/private tap only.
# This is NOT official Homebrew core support and is not published as a tap yet.
# Fill sha256 from the immutable v2.3.1 release tarball when that tag is final.
class DataRelayLink < Formula
  desc "Data Relay Link client for Apple Silicon macOS"
  homepage "https://github.com/datarelay-labs/data-relay-link"
  url "https://github.com/datarelay-labs/data-relay-link/archive/refs/tags/v2.3.1.tar.gz"
  version "2.3.1"
  sha256 "REPLACE_AT_TAG_TIME_WITH_RELEASE_TARBALL_SHA256"
  license "MIT"

  depends_on arch: :arm64
  depends_on :macos
  depends_on macos: :big_sur

  def install
    libexec.install "install-client.sh", "uninstall-client.sh", "VERSION",
                    "release-manifest.json", "lib", "tools", "client"
    %w[drlink frp-client].each do |name|
      (bin/name).write <<~SH
        #!/bin/bash
        exec "#{libexec}/tools/#{name}" "$@"
      SH
      chmod 0755, bin/name
    end
  end

  def caveats
    <<~EOS
      This formula installs the client tools only. Use the enrollment command
      generated by your Data Relay Link server to enroll and start the LaunchDaemon.
    EOS
  end

  test do
    assert_match "PROJECT_VERSION=2.3.1", (libexec/"VERSION").read
    assert_predicate bin/"drlink", :executable?
  end
end
